# Generated by Django 5.2.17 on 2026-09-12 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="como se llama")),
                (
                    "comercio",
                    models.CharField(max_length=120, verbose_name="como se llama su negocio"),
                ),
                ("telefono", models.CharField(max_length=25, verbose_name="telefono")),
                ("correo", models.EmailField(blank=True, max_length=254, verbose_name="correo")),
                ("mensaje", models.TextField(blank=True, verbose_name="lo que escribio")),
                (
                    "origen",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="desde donde escribio"
                    ),
                ),
                ("origen_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nuevo", "Sin atender"),
                            ("atendido", "Ya le escribimos"),
                            ("convertido", "Abrio su tienda"),
                            ("descartado", "No era para nosotros"),
                        ],
                        default="nuevo",
                        max_length=12,
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas nuestras")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("atendido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contactos_atendidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(fields=["estado", "-creado_en"], name="contacto_estado_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("telefono",), name="un_contacto_por_telefono")
                ],
            },
        ),
    ]
